-- AlterTable
ALTER TABLE `Order` MODIFY `status` ENUM('PENDIENTE', 'AUTORIZADO', 'RECHAZADO', 'COMPLETADO', 'OBSERVADO', 'BORRADOR', 'null') NULL;

-- AlterTable
ALTER TABLE `OrderStatusHistory` MODIFY `status` ENUM('PENDIENTE', 'AUTORIZADO', 'RECHAZADO', 'COMPLETADO', 'OBSERVADO', 'BORRADOR', 'null') NULL;
