import { test, expect } from '@playwright/test';

test('Insertar auto y activarle garantia', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('button', { name: 'Cargar Auto' }).click();
  await page.locator('input[name="vin"]').click();
  await page.locator('input[name="vin"]').fill('00000000000000003');
  await page.locator('input[name="brand"]').click();
  await page.locator('input[name="brand"]').press('CapsLock');
  await page.locator('input[name="brand"]').fill('AAAAA');
  await page.locator('input[name="model"]').click();
  await page.locator('input[name="model"]').fill('AAAAA');
  await page.locator('input[name="licensePlate"]').click();
  await page.locator('input[name="model"]').fill('AAAAAA');
  await page.locator('input[name="licensePlate"]').fill('AAAAA');
  await page.locator('input[name="licensePlate"]').click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('2025');
  await page.locator('input[name="engineNumber"]').click();
  await page.locator('input[name="engineNumber"]').fill('AAAAA');
  await page.locator('input[name="type"]').click();
  await page.locator('input[name="type"]').fill('AAAAA');
  await page.locator('input[name="certificateNumber"]').click();
  await page.locator('input[name="certificateNumber"]').fill('2021');
  await page.locator('input[name="saleDate"]').fill('2025-10-16');
  await page.locator('input[name="importDate"]').fill('2025-10-17');
  await page.getByRole('combobox').selectOption('1');
  await page.getByRole('button', { name: 'Guardar' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => { });
  });
  await page.goto('http://localhost:3000/');
  await page.getByRole('button', { name: 'Activar Garantia' }).click();
  await page.locator('input[name="vin"]').click();
  await page.locator('input[name="vin"]').fill('00000000000000003');
  await page.getByTestId('search-vehicle-button').click();
  await page.locator('input[name="user"]').fill('Fabio Summa');
  await page.locator('input[name="clientName"]').fill('cliente');
  await page.locator('input[name="clientSurname"]').fill('cliente');
  await page.locator('input[name="clientEmail"]').fill('c@gmail.com');
  await page.locator('input[name="clientPhone"]').fill('12345678');
  await page.locator('input[name="clientDirection"]').fill('cliente');
  await page.locator('select[name="clientProvince"]').selectOption('Buenos Aires');
  await page.locator('select[name="clientLocality"]').selectOption('Mar del Plata');
  await page.getByRole('button', { name: 'Guardar' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => { });
  });
  await page.getByRole('button', { name: 'Guardar' }).click();
  await page.goto('http://localhost:3000/');
  await page.getByRole('link', { name: 'Garantías' }).click();
  await page.locator('div').filter({ hasText: /^Desde$/ }).getByRole('textbox').fill('2024-10-01');
  await page.locator('div').filter({ hasText: /^VIN$/ }).getByRole('textbox').fill('00000000000000003');
  await page.getByRole('button', { name: 'Buscar' }).click();
  await expect(page.locator('tbody')).toContainText('00000000000000003');
});